-- ==========================================
-- MEDITRACK: FULL SUPABASE DATABASE SCHEMA
-- ==========================================
-- INSTRUCTIONS: Run this complete script in the Supabase SQL Editor.
-- ==========================================

-- Enable Necessary Extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- --------------------------------------------------------
-- 1. Tables: Base Definitions
-- --------------------------------------------------------

-- Administrative Tables
CREATE TABLE IF NOT EXISTS tbl_admin (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    admin_email VARCHAR(255) UNIQUE NOT NULL
);

-- Location Tables
CREATE TABLE IF NOT EXISTS tbl_district (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    district_name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS tbl_place (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    place_name VARCHAR(255) NOT NULL,
    district_id BIGINT REFERENCES tbl_district(id) ON DELETE CASCADE
);

-- Core User Tables
CREATE TABLE IF NOT EXISTS tbl_patient (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_name VARCHAR(255) NOT NULL,
    patient_email VARCHAR(255) UNIQUE NOT NULL,
    patient_password VARCHAR(255) NOT NULL,
    patient_contact VARCHAR(255),
    patient_dob DATE,
    patient_gender VARCHAR(50),
    patient_address TEXT,
    patient_photo TEXT,
    place_id BIGINT REFERENCES tbl_place(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS tbl_caregiver (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    caregiver_name VARCHAR(255) NOT NULL,
    caregiver_email VARCHAR(255) UNIQUE NOT NULL,
    caregiver_password VARCHAR(255) NOT NULL,
    caregiver_dob DATE,
    caregiver_contact VARCHAR(255),
    caregiver_photo TEXT,
    caregiver_address TEXT,
    caregiver_status INT DEFAULT 0, -- 0: Pending, 1: Approved, 2: Rejected
    caregiver_certificate TEXT,
    caregiver_idproof TEXT,
    caregiver_gender VARCHAR(50),
    caregiver_experience VARCHAR(255),
    place_id BIGINT REFERENCES tbl_place(id) ON DELETE SET NULL
);

-- Medicine & Health Tables
CREATE TABLE IF NOT EXISTS tbl_medicinecategory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medicinecategory_name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS tbl_medicine (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medicine_name VARCHAR(255) NOT NULL,
    medicine_description TEXT,
    medicine_fromdate TIMESTAMP,
    medicine_todate TIMESTAMP,
    medicine_time VARCHAR(20), -- Reminders/Schedule time
    medicine_status INT DEFAULT 1,
    medicinecategory_id BIGINT REFERENCES tbl_medicinecategory(id) ON DELETE SET NULL,
    patient_id BIGINT REFERENCES tbl_patient(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS tbl_stock (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_count INT DEFAULT 0,
    medicine_id BIGINT REFERENCES tbl_medicine(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS tbl_vitals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vital_type VARCHAR(255) NOT NULL,
    vital_value VARCHAR(255) NOT NULL,
    patient_id BIGINT REFERENCES tbl_patient(id) ON DELETE CASCADE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tbl_intake_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medicine_id BIGINT REFERENCES tbl_medicine(id) ON DELETE CASCADE,
    patient_id BIGINT REFERENCES tbl_patient(id) ON DELETE CASCADE,
    intake_datetime TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tbl_emergency_contact (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_name VARCHAR(255) NOT NULL,
    contact_phone VARCHAR(255) NOT NULL,
    contact_relation VARCHAR(255),
    patient_id BIGINT REFERENCES tbl_patient(id) ON DELETE CASCADE
);

-- Interaction Tables
CREATE TABLE IF NOT EXISTS tbl_request (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT REFERENCES tbl_patient(id) ON DELETE CASCADE,
    caregiver_id BIGINT REFERENCES tbl_caregiver(id) ON DELETE CASCADE,
    request_details TEXT,
    request_status INT DEFAULT 0 -- 0: Pending, 1: Accepted, 2: Rejected
);

CREATE TABLE IF NOT EXISTS tbl_chat (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_content TEXT,
    chat_frompatient BIGINT REFERENCES tbl_patient(id) ON DELETE CASCADE,
    chat_topatient BIGINT REFERENCES tbl_patient(id) ON DELETE CASCADE,
    chat_fromcaregiver BIGINT REFERENCES tbl_caregiver(id) ON DELETE CASCADE,
    chat_tocaregiver BIGINT REFERENCES tbl_caregiver(id) ON DELETE CASCADE,
    chat_file TEXT,
    chat_isseen INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tbl_complaint (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    complaint_title VARCHAR(255),
    complaint_content TEXT,
    caregiver_id BIGINT REFERENCES tbl_caregiver(id) ON DELETE CASCADE,
    patient_id BIGINT REFERENCES tbl_patient(id) ON DELETE CASCADE,
    complaint_reply TEXT,
    complaint_reply_status INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- --------------------------------------------------------
-- 2. Row Level Security (RLS) - "Allow All" Policies
-- --------------------------------------------------------

-- Enable RLS and create generic Allow All policies for each table
DO $$
DECLARE
    t_name text;
BEGIN
    FOR t_name IN SELECT tablename FROM pg_tables WHERE schemaname = 'public' LOOP
        EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY;', t_name);
        EXECUTE format('DROP POLICY IF EXISTS "Allow all for %I" ON public.%I', t_name, t_name);
        EXECUTE format('CREATE POLICY "Allow all for %I" ON public.%I FOR ALL USING (true) WITH CHECK (true);', t_name, t_name);
    END LOOP;
END;
$$;

-- --------------------------------------------------------
-- 3. Live Subscriptions (Realtime for Chat System)
-- --------------------------------------------------------

-- Create/Recreate Realtime Publication
BEGIN;
  DROP PUBLICATION IF EXISTS supabase_realtime;
  CREATE PUBLICATION supabase_realtime;
COMMIT;

-- Subscribe the Chat Table for Instant Messaging
ALTER PUBLICATION supabase_realtime ADD TABLE tbl_chat;

-- --------------------------------------------------------
-- 4. Storage Buckets and Policies
-- --------------------------------------------------------

-- Initialize Storage Buckets for MediTrack
INSERT INTO storage.buckets (id, name, public) 
VALUES 
    ('patient_photos', 'patient_photos', true),
    ('caregiver_photos', 'caregiver_photos', true),
    ('caregiver_idproofs', 'caregiver_idproofs', true),
    ('chat_files', 'chat_files', true)
ON CONFLICT (id) DO NOTHING;

-- Create ALL ACCESS policies for storage buckets
-- Note: 'storage.objects' policies apply to all files in all buckets.
DROP POLICY IF EXISTS "Give all users full access to patient_photos" ON storage.objects;
CREATE POLICY "Give all users full access to patient_photos" ON storage.objects 
FOR ALL USING (bucket_id = 'patient_photos') WITH CHECK (bucket_id = 'patient_photos');

DROP POLICY IF EXISTS "Give all users full access to caregiver_photos" ON storage.objects;
CREATE POLICY "Give all users full access to caregiver_photos" ON storage.objects 
FOR ALL USING (bucket_id = 'caregiver_photos') WITH CHECK (bucket_id = 'caregiver_photos');

DROP POLICY IF EXISTS "Give all users full access to caregiver_idproofs" ON storage.objects;
CREATE POLICY "Give all users full access to caregiver_idproofs" ON storage.objects 
FOR ALL USING (bucket_id = 'caregiver_idproofs') WITH CHECK (bucket_id = 'caregiver_idproofs');

DROP POLICY IF EXISTS "Give all users full access to chat_files" ON storage.objects;
CREATE POLICY "Give all users full access to chat_files" ON storage.objects 
FOR ALL USING (bucket_id = 'chat_files') WITH CHECK (bucket_id = 'chat_files');

-- --------------------------------------------------------
-- 5. Final Checks
-- --------------------------------------------------------
-- Ensure standard Supabase roles are granted permissions to public
GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL ROUTINES IN SCHEMA public TO anon, authenticated, service_role;
